image: gcc:latest

options:
  docker:  true
  size: 2x

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  
  services:
    docker:
      memory:  4096
      
pipelines:
  default:
    - step:  
        caches:
          - sonar
        script:
          - export SONAR_SCANNER_VERSION=4.4.0.2170
          - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
          - export BW_OUTPUT=$HOME/.sonar/bw-output
          - mkdir -p $BW_OUTPUT
          - apt -y install curl
          - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
          - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
          - export SONAR_SCANNER_OPTS="-server"
          - curl --create-dirs -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          - unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          - export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
          - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.14.0-rc1
          - export PATH=/opt/atlassian/pipelines/agent/build/bin:$PATH
          - arduino-cli core update-index --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          - arduino-cli core install adafruit:samd --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          - arduino-cli lib install "Adafruit SPIFlash"
          #- echo $PWD
          #- ls
          - build-wrapper-linux-x86-64 --out-dir $BW_OUTPUT /root/.arduino15/packages/adafruit/tools/arm-none-eabi-gcc/9-2019q4/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions "-D__SKETCH_NAME__=\"\"\"build.ino\"\"\"" -w -x c++ -E -CC -DF_CPU=120000000L -DARDUINO=10607 -DARDUINO_METRO_M4 -DARDUINO_ARCH_SAMD -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\"" -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DENABLE_CACHE -Os -DVARIANT_QSPI_BAUD_DEFAULT=50000000 -D__SAMD51J19A__ -DADAFRUIT_METRO_M4_EXPRESS -D__SAMD51__ -DUSB_VID=0x239A -DUSB_PID=0x8020 -DUSBCON -DUSB_CONFIG_POWER=100 "-DUSB_MANUFACTURER=\"Adafruit LLC\"" "-DUSB_PRODUCT=\"Adafruit Metro M4\"" -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/tinyusb/src -D__FPU_PRESENT -DARM_MATH_CM4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -I/root/.arduino15/packages/adafruit/tools/CMSIS/5.4.0/CMSIS/Core/Include/ -I/root/.arduino15/packages/adafruit/tools/CMSIS/5.4.0/CMSIS/DSP/Include/ -I/root/.arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/ -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/cores/arduino -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/variants/metro_m4 -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/libraries/Wire -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/libraries/SPI -I/root/.arduino15/packages/adafruit/hardware/samd/1.6.4/libraries/Adafruit_ZeroDMA -I/root/Arduino/libraries/Adafruit_SPIFlash/src -I/root/Arduino/libraries/SdFat_-_Adafruit_Fork/src Adafruit_GFX.cpp -o $BW_OUTPUT/Adafruit_GFX.o
          - cd $BW_OUTPUT
          - sonar-scanner -Dsonar.cfamily.build-wrapper-output=$BW_OUTPUT